/* Run Script Customer */
export const RUN_SCRIPT_CUSTOMER = "RUN_SCRIPT_CUSTOMER"
export const RUN_SCRIPT_CUSTOMER_SUCCESS = "RUN_SCRIPT_CUSTOMER_SUCCESS"
export const RUN_SCRIPT_CUSTOMER_FAIL = "RUN_SCRIPT_CUSTOMER_FAIL"

/* Run Script Booking */
export const RUN_SCRIPT_BOOKING = "RUN_SCRIPT_BOOKING"
export const RUN_SCRIPT_BOOKING_SUCCESS = "RUN_SCRIPT_BOOKING_SUCCESS"
export const RUN_SCRIPT_BOOKING_FAIL = "RUN_SCRIPT_BOOKING_FAIL"

/* Run REmove Script Booking */
export const RUN_REMOVE_SCRIPT_BOOKING = "RUN_REMOVE_SCRIPT_BOOKING"
export const RUN_REMOVE_SCRIPT_BOOKING_SUCCESS =
  "RUN_REMOVE_SCRIPT_BOOKING_SUCCESS"
export const RUN_REMOVE_SCRIPT_BOOKING_FAIL = "RUN_REMOVE_SCRIPT_BOOKING_FAIL"
