/* Get Booking Slot */
export const GET_BOOKING_SLOT = "GET_BOOKING_SLOT"
export const GET_BOOKING_SLOT_SUCCESS = "GET_BOOKING_SLOT_SUCCESS"
export const GET_BOOKING_SLOT_FAIL = "GET_BOOKING_SLOT_FAIL"

/* Get Car In Garage */
export const GET_CAR_IN_GARAGE = "GET_CAR_IN_GARAGE"
export const GET_CAR_IN_GARAGE_SUCCESS = "GET_CAR_IN_GARAGE_SUCCESS"
export const GET_CAR_IN_GARAGE_FAIL = "GET_CAR_IN_GARAGE_FAIL"
