/* ORDER_SERVICE LIST */
export const GET_ORDER_SERVICE_LIST = "GET_ORDER_SERVICE_LIST"
export const GET_ORDER_SERVICE_LIST_SUCCESS = "GET_ORDER_SERVICE_LIST_SUCCESS"
export const GET_ORDER_SERVICE_LIST_FAIL = "GET_ORDER_SERVICE_LIST_FAIL"

/* ORDER_SERVICE DETAIL */
export const GET_ORDER_SERVICE_DETAIL = "GET_ORDER_SERVICE_DETAIL"
export const GET_ORDER_SERVICE_DETAIL_SUCCESS =
  "GET_ORDER_SERVICE_DETAIL_SUCCESS"
export const GET_ORDER_SERVICE_DETAIL_FAIL = "GET_ORDER_SERVICE_DETAIL_FAIL"
